In local PC setup, like in Anaconda, install Numpy using :

or

In [2]:
pip install numpy

[Documentation](https://numpy.org/doc/)

[w3school](https://www.w3schools.com/python/numpy/default.asp)

In [2]:
import numpy as np

#Numpy Arrays

Numpy arrays : vectors(1D arrays) and matrices(2D arrays).

Converting a list to numpy array

In [4]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

Converting list of lists to matrix

In [5]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_list)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we gave a list as input, np.array() returned a vector but when we gave a list of lists, we got a matrix as output.

Arrange numbers in a range

In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we want to customize step number instead of 1,we provide that step number as 3rd parameter.

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Array of all zeroes of size n

```
np.zeros(n)
```



In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2D zeros matrix

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Array of all ones of size n


```
np.ones(n)
```



In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**linspace(start,stop,num)**

num is the number of samples to generate which determines the length of the output array.

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#Random number generation

We can use rand method of random module to generate numbers.

In [13]:
np.random.rand(5)

array([0.20961275, 0.14599756, 0.73836949, 0.93007447, 0.51415877])

In [14]:
np.random.rand(2,3)

array([[0.06918879, 0.6862917 , 0.98930756],
       [0.96573801, 0.86301344, 0.8396634 ]])

In [15]:
np.random.randn(5)

array([ 1.21427409,  0.05884743, -0.39175333,  0.60411909,  0.53799011])

**rand**: generates random numbers from a uniform distribution over [0,1)

**randn** : generates random numbers from a standard normal distribution ( mean 0, std 1)

**randint** method from numpy.random module generates random integers from a specifies [low,high) range.

Generates a random integer from [0,11)

In [16]:
np.random.randint(0,11)

0

Generates a 1D array of 5 random integers between [0,11)

In [17]:
np.random.randint(0,11,5)

array([1, 9, 8, 4, 1])

Generates a 2D array of shape (2,3) with random integers between [0,11).

In [18]:
np.random.randint(0,11,(2,3))

array([[ 5,  3, 10],
       [ 8,  9,  6]])

**Reshaping an array**

using `reshape()`

In [19]:
arr = np.random.randint(0,50,10)
arr

array([ 6, 29, 15, 21,  2, 11,  3,  5, 24, 39])

In [20]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

Note the error! You cannot give a size that violates the size of the original array. Here, the size of the actual array was 10, but we wanted to reshape it to a 5x5 matrix which requires 25 samples. Hence the error.

In [21]:
arr.reshape(2,5)

array([[ 6, 29, 15, 21,  2],
       [11,  3,  5, 24, 39]])

#Finding different information about the array


* max : `max()`
* min : `min()`
* position of maximum value : `argmax()`
* position of minimum value : `argmin()`
* dimension of the array : `shape`
* data type of the array : `dtype`

In [22]:
arr.max()

39

In [23]:
arr.min()

2

In [24]:
arr.argmax()

9

In [25]:
arr.argmin()

4

In [26]:
arr.shape

(10,)

Note that, by (10,) it means it is an 1D array of 10 samples.

In [ ]:
arr = arr.reshape(5,2)
arr

In [28]:
arr.shape

(5, 2)

In [29]:
arr.dtype

dtype('int64')

#NumPy Indexing and Selection

Indexing is like python indexing , i.e, 0-based

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
print(arr[3])

4


We can print a range of numbers by giving [start,end).

In [34]:
print(arr[1:5])

[2 3 4 5]


We can also **broadcast** values specifying the range.

In [36]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

##2D array indexing

You can use double bracket (for example, arr[0][1] ) or single bracket (for example, arr[0,1]) method.

In [13]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# double bracket
arr[1][3]

9

In [15]:
# single bracket
arr[1,3]

9

**Slicing in 2D array**

In [6]:
arr[:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

The above example slices array from row[0,2) and column [1,5).

In [7]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

##Copy and view

Copy - copy is a new array which owns the data and any changes made to the copy will not affect the original array and vice versa.

View - Does not own the data and any changes made to the view will affect the original array and vice versa.

Why do we need copy and what happens with view?

In [39]:
arr = np.arange(1,11)
slice_of_arr = arr[0:6]

In [40]:
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [42]:
slice_of_arr[:] = 10

In [43]:
slice_of_arr

array([10, 10, 10, 10, 10, 10])

In [44]:
arr

array([10, 10, 10, 10, 10, 10,  7,  8,  9, 10])

Note the above example. Here we tried to change value of the slice_of_array but the change is reflected in the actual array too. It is because slice_of_array is view of the original array.

If we want to modify without changing the original array, we need to use copy.

Method used to create copy :


```
copy()
```



In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Now the modification is not reflected in the original array.

**Learning point :**
If you want to modify without reflecting the modification in the original array, create its copy explicitly. If you do not create a copy, it will provide a view and hence the modification will be both on the view and original array.

##Selection

Conditional selection : Selecting based on any condition.

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

The above code returns value of the array where value is greater than 5.

The above code could be simply written as :

In [12]:
arr = np.arange(1,11)
print(arr[arr > 5])

[ 6  7  8  9 10]


#NumPy opearations

You can perform all the mathematical operations in NumPy arrays. For example :

In [22]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
arr / arr

<ipython-input-26-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Note that due to division by 0, the first index contains **nan**(not a number)

**Scalar operations**

In [27]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

**ufuncs**

ufuncs stands for Universal Functions.

You can follow this blog to get an idea about the universal functions:
https://w3schools.com/python/numpy/numpy_ufunc.asp

A few examples on universal functions are noted below :

In [29]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [30]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [31]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [34]:
np.max(arr)

# similar to arr.max()

10